- name: Upload To Github Release
  # You may pin to the exact commit or the version.
  # uses: xresloader/upload-to-github-release@0b497b306a775554a3dd3cfb80dec8e7de4ae969
  uses: xresloader/upload-to-github-release@v1.3.12
  with:
    # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
    file: # default is 
    # The files or file patterns to delete before uploading new files. You can delete multiple files by split them by semicolon. You can use the glob pattern to find the files.
    delete_file: # optional, default is 
    # If you need to overwrite existing files, add overwrite: true to the with.
    overwrite: # optional, default is false
    # The resultant deployment is a draft Release that only repository collaborators can see. This gives you an opportunity to examine and edit the draft release.
    draft: # optional, default is 
    # The resultant deployment is a Prerelease. This gives you an opportunity to examine and edit the prerelease.
    prerelease: # optional, default is 
    # With tags: true, your Releases deployment will trigger if and only if the build is a tagged build.
    tags: # optional, default is false
    # Only work on these branches(splited by semicolon), set to nothing to accept all branches.
    branches: # optional, default is 
    # With verbose: true, be verbose.
    verbose: # optional, default is false
    # Set custom tag name.
    tag_name: # optional, default is 
    # If try to update latest release.
    update_latest_release: # optional, default is false
    # Set release id to update.If release_id is set, this step will fail if we can not find it.
    release_id: # optional, default is 
    # Set release name when create a new release.
    default_release_name: # optional, default is 
    # Set the owner of target repository(default: current user/origanization).
    target_owner: # optional, default is 
    # Set target repository(default: current repository).
    target_repo: # optional, default is 
    # How many releases to check when we find a existing draft release.(default: 32).
    find_draft_release_count: # optional, default is 32
